# Default values for k8s-poolprovider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  namespace: azuredevops
  name: azure-pipelines-pool

rbac:
  clusterRole: admin

image:
  repository: ykholodkov/k8s-poolprovider
  tag: v1.25s
  pullPolicy: IfNotPresent

azurepipelines:
  VSTS_SECRET: ""
